### ISSUE TITLE
Bug : some `components` in the `release.json` do not have a `version` JSON Property

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [gravitee-lab/GraviteeCiCdOrchestrator#26]
* The following Error is thrown  : 

```bash
      "gravitee-management-webui",

      "gravitee-portal-webui"

    ]

  ]

}]

/graviteeio/cicd/dist/modules/manifest/ReleaseManifestFilter.js:69

            if (component.version.includes('-SNAPSHOT')) {

                                  ^



TypeError: Cannot read property 'includes' of undefined

    at /graviteeio/cicd/dist/modules/manifest/ReleaseManifestFilter.js:69:35

    at Array.forEach (<anonymous>)

    at ReleaseManifestFilter.filter (/graviteeio/cicd/dist/modules/manifest/ReleaseManifestFilter.js:68:41)

    at ReleaseManifestFilter.buildExecutionPlan (/graviteeio/cicd/dist/modules/manifest/ReleaseManifestFilter.js:140:14)

    at Object.<anonymous> (/graviteeio/cicd/dist/index.js:43:40)

    at Module._compile (internal/modules/cjs/loader.js:1075:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)

    at Module.load (internal/modules/cjs/loader.js:940:32)

    at Function.Module._load (internal/modules/cjs/loader.js:781:14)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! GraviteeReleaseOrchestrator@0.0.2 start: `node ./dist/index.js "-s" "mvn_release" "--dry-run" "false"`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the GraviteeReleaseOrchestrator@0.0.2 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2020-09-24T03_33_40_140Z-debug.log

CircleCI received exit code 0

```
* because for some  `components` in `release.json`, there is no `version` JSON property

Fix is : 

* for any such component, the `version` JSON property is infered from the top-level `version` JSON property in `release.json` 
* Bug fix has to be applied on the `ReleaseManifestParser` module

**Comment by Jean-Baptiste-Lasselle** [comment]
issue fixed see https://app.circleci.com/pipelines/github/gravitee-lab/release/55/workflows/0ce1890e-4f52-48fa-8cbd-99b20cff159e/jobs/62
